version: '3.8'

networks: 
  net:
    external: true

services:
  traefik:
    image: traefik:v1.7-alpine  # Gunakan versi Alpine untuk image yang lebih ringan
    container_name: traefik
    restart: always
    command:
      - "--web"
      - "--docker"
      - "--docker.domain=docker.local"
      - "--docker.watch"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--acme=true"
      - "--acme.email=admin@ismartdds.com"
      - "--acme.storage=/letsencrypt/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - net

  dashboard-case-service:
    container_name: dashboard-case-service
    build:
      context: ./workspace/dashboard-case-service
      dockerfile: .docker/Dockerfile
    env_file:
      - ./workspace/dashboard-case-service/.deployment/.env
    volumes: 
      - ./workspace/dashboard-case-service:/var/www/html
    ports:
      - "9080:8080"
    #depends_on:
     # - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:annievip.ismartdds.com"
      - "traefik.port=8080"
      - "traefik.docker.network=net"
    networks:
      - net

  case-service:
    container_name: case-service
    env_file: .env
    build:
      context: ./workspace/case-service
      dockerfile: .docker/Dockerfile
    volumes:
      - ./workspace/case-service:/app:rw,delegated
      - type: bind
        # source: ./workspace/case-service/attach
        # source: C:/alwin/soft/annie doc/attach
        source: C:/inetpub/wwwroot/annievip.ismartdds.com/ANNIEVIP_Case_Folder
        target: /var/attach
    ports:
      - "8081:9999"
   # depends_on:
    #  - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:annievipbe.ismartdds.com"
      - "traefik.port=9999"
      - "traefik.docker.network=net"
      - "traefik.frontend.headers.AccessControlAllowMethods=GET,POST,OPTIONS"
      - "traefik.frontend.headers.AccessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.frontend.headers.XFrameOptions=SAMEORIGIN"
      - "traefik.frontend.headers.XXSSProtection=1; mode=block"
    networks:
      - net
