package util

type GetDataAnnieRequest struct {
	TimePointId string `json:"TimePointId" valid:"required"`
}

type GetDataAnnieResponse []struct {
	TimePointID                interface{} `json:"TimePointId"`
	Email                      interface{} `json:"Email"`
	PatientID                  interface{} `json:"PatientId"`
	TimePointName              interface{} `json:"TimePointName"`
	TimePointDate              interface{} `json:"TimePointDate"`
	CustomerNumber             interface{} `json:"CustomerNumber"`
	TreatmentNote              interface{} `json:"TreatmentNote"`
	ImageIntraOralRightID      interface{} `json:"Image_IntraOralRight_Id"`
	ImageIntraOralRight        interface{} `json:"Image_IntraOralRight"`
	ImageIntraOralRightResult  interface{} `json:"Image_IntraOralRight_Result"`
	ImageIntraOralRightDate    interface{} `json:"Image_IntraOralRight_Date"`
	ImageIntraOralFrontID      interface{} `json:"Image_IntraOralFront_Id"`
	ImageIntraOralFront        interface{} `json:"Image_IntraOralFront"`
	ImageIntraOralFrontResult  interface{} `json:"Image_IntraOralFront_Result"`
	ImageIntraOralFrontDate    interface{} `json:"Image_IntraOralFront_Date"`
	ImageIntraOralLeftID       interface{} `json:"Image_IntraOralLeft_Id"`
	ImageIntraOralLeft         interface{} `json:"Image_IntraOralLeft"`
	ImageIntraOralLeftResult   interface{} `json:"Image_IntraOralLeft_Result"`
	ImageIntraOralLeftDate     interface{} `json:"Image_IntraOralLeft_Date"`
	ImageIntraOralUpperID      interface{} `json:"Image_IntraOralUpper_Id"`
	ImageIntraOralUpper        interface{} `json:"Image_IntraOralUpper"`
	ImageIntraOralUpperResult  interface{} `json:"Image_IntraOralUpper_Result"`
	ImageIntraOralUpperDate    interface{} `json:"Image_IntraOralUpper_Date"`
	ImageIntraOralLowerID      interface{} `json:"Image_IntraOralLower_Id"`
	ImageIntraOralLower        interface{} `json:"Image_IntraOralLower"`
	ImageIntraOralLowerResult  interface{} `json:"Image_IntraOralLower_Result"`
	ImageIntraOralLowerDate    interface{} `json:"Image_IntraOralLower_Date"`
	ImageProfileID             interface{} `json:"Image_Profile_Id"`
	ImageProfile               interface{} `json:"Image_Profile"`
	ImageProfileDate           interface{} `json:"Image_Profile_Date"`
	ImageProfileSmileID        interface{} `json:"Image_ProfileSmile_Id"`
	ImageProfileSmile          interface{} `json:"Image_ProfileSmile"`
	ImageProfileSmileDate      interface{} `json:"Image_ProfileSmile_Date"`
	ImageProfileNoSmileID      interface{} `json:"Image_ProfileNoSmile_Id"`
	ImageProfileNoSmile        interface{} `json:"Image_ProfileNoSmile"`
	ImageProfileNoSmileDate    interface{} `json:"Image_ProfileNoSmile_Date"`
	ImageLateralID             interface{} `json:"Image_Lateral_Id"`
	ImageLateral               interface{} `json:"Image_Lateral"`
	ImageLateralResult         interface{} `json:"Image_Lateral_Result"`
	ImageLateralDate           interface{} `json:"Image_Lateral_Date"`
	ImageLateralConfirm        interface{} `json:"Image_Lateral_Confirm"`
	ImageLateralConfirmDate    interface{} `json:"Image_Lateral_Confirm_Date"`
	ImageLateralDownload       interface{} `json:"Image_Lateral_Download"`
	ImageLateralProgress       interface{} `json:"Image_Lateral_Progress"`
	ImageFrontalID             interface{} `json:"Image_Frontal_Id"`
	ImageFrontal               interface{} `json:"Image_Frontal"`
	ImageFrontalResult         interface{} `json:"Image_Frontal_Result"`
	ImageFrontalDate           interface{} `json:"Image_Frontal_Date"`
	ImageFrontalConfirm        interface{} `json:"Image_Frontal_Confirm"`
	ImageFrontalConfirmDate    interface{} `json:"Image_Frontal_Confirm_Date"`
	ImageFrontalDownload       interface{} `json:"Image_Frontal_Download"`
	ImageFrontalProgress       interface{} `json:"Image_Frontal_Progress"`
	ImageUpperID               interface{} `json:"Image_Upper_Id"`
	ImageUpper                 interface{} `json:"Image_Upper"`
	ImageUpperResult           interface{} `json:"Image_Upper_Result"`
	ImageUpperDate             interface{} `json:"Image_Upper_Date"`
	ImageUpperConfirm          interface{} `json:"Image_Upper_Confirm"`
	ImageUpperConfirmDate      interface{} `json:"Image_Upper_Confirm_Date"`
	ImageUpperDownload         interface{} `json:"Image_Upper_Download"`
	ImageUpperProgress         interface{} `json:"Image_Upper_Progress"`
	ImageLowerID               interface{} `json:"Image_Lower_Id"`
	ImageLower                 interface{} `json:"Image_Lower"`
	ImageLowerResult           interface{} `json:"Image_Lower_Result"`
	ImageLowerDate             interface{} `json:"Image_Lower_Date"`
	ImageLowerConfirm          interface{} `json:"Image_Lower_Confirm"`
	ImageLowerConfirmDate      interface{} `json:"Image_Lower_Confirm_Date"`
	ImageLowerDownload         interface{} `json:"Image_Lower_Download"`
	ImageLowerProgress         interface{} `json:"Image_Lower_Progress"`
	ImagePanoramicID           interface{} `json:"Image_Panoramic_Id"`
	ImagePanoramic             interface{} `json:"Image_Panoramic"`
	ImagePanoramicResult       interface{} `json:"Image_Panoramic_Result"`
	ImagePanoramicDate         interface{} `json:"Image_Panoramic_Date"`
	ImageBiteWingID            interface{} `json:"Image_BiteWing_Id"`
	ImageBiteWing              interface{} `json:"Image_BiteWing"`
	ImageBiteWingResult        interface{} `json:"Image_BiteWing_Result"`
	ImageBiteWingDate          interface{} `json:"Image_BiteWing_Date"`
	ScoreDentalAssessment      interface{} `json:"Score_DentalAssessment"`
	Comment                    interface{} `json:"Comment"`
	IsActive                   interface{} `json:"IsActive"`
	AssessmentDate             interface{} `json:"AssessmentDate"`
	SubmitDuration             interface{} `json:"SubmitDuration"`
	ProcessDuration            interface{} `json:"ProcessDuration"`
	LinkVerifyLateral          interface{} `json:"LinkVerify_Lateral"`
	LinkVerifyFrontal          interface{} `json:"LinkVerify_Frontal"`
	LinkVerifyUpperArch        interface{} `json:"LinkVerify_UpperArch"`
	LinkVerifyLowerArch        interface{} `json:"LinkVerify_LowerArch"`
	CountFindingLateral        interface{} `json:"Count_Finding_Lateral"`
	CountFindingFrontal        interface{} `json:"Count_Finding_Frontal"`
	CountFindingUpper          interface{} `json:"Count_Finding_Upper"`
	CountFindingLower          interface{} `json:"Count_Finding_Lower"`
	GenerateReport1            interface{} `json:"GenerateReport1"`
	GenerateReport2            interface{} `json:"GenerateReport2"`
	GenerateReport3            interface{} `json:"GenerateReport3"`
	LateralFindingStatus       interface{} `json:"Lateral_Finding_Status"`
	FrontalFindingStatus       interface{} `json:"Frontal_Finding_Status"`
	LowerFindingStatus         interface{} `json:"Lower_Finding_Status"`
	UpperFindingStatus         interface{} `json:"Upper_Finding_Status"`
	LateralConfirmStatus       interface{} `json:"Lateral_Confirm_Status"`
	FrontalConfirmStatus       interface{} `json:"Frontal_Confirm_Status"`
	UpperConfirmStatus         interface{} `json:"Upper_Confirm_Status"`
	LowerConfirmStatus         interface{} `json:"Lower_Confirm_Status"`
	Report01DentalEvaluation   interface{} `json:"Report_01_Dental_Evaluation"`
	Report02ProblemList        interface{} `json:"Report_02_Problem_List"`
	Report03TreatmentRationale interface{} `json:"Report_03_Treatment_Rationale"`
	Report04CaseEvaluation     interface{} `json:"Report_04_Case_Evaluation"`
	Report05DentalFindings     interface{} `json:"Report_05_Dental_Findings"`
	Report06SkeletalFindings   interface{} `json:"Report_06_Skeletal_Findings"`
	Report07TracingMeasurement interface{} `json:"Report_07_Tracing_Measurement"`
	Report08SequenceWorksheet  interface{} `json:"Report_08_Sequence_Worksheet"`
	Report09Legacy             interface{} `json:"Report_09_Legacy"`
	Report10HLDSummary         interface{} `json:"Report_10_HLD_Summary"`
	ReportDate16               interface{} `json:"ReportDate_1_6"`
	ReportDate79               interface{} `json:"ReportDate_7_9"`
	ReportDate10               interface{} `json:"ReportDate_10"`
	TimePointProgress          interface{} `json:"TimePointProgress"`
	ReportProgress             interface{} `json:"ReportProgress"`
	AutoCorrectLateral         interface{} `json:"AutoCorrect_Lateral"`
	AutoCorrectFrontal         interface{} `json:"AutoCorrect_Frontal"`
	AutoCorrectUpper           interface{} `json:"AutoCorrect_Upper"`
	AutoCorrectLower           interface{} `json:"AutoCorrect_Lower"`
	CaseNextStepInfo           interface{} `json:"Case_NextStepInfo"`
	CaseRequirementInfo        interface{} `json:"Case_RequirementInfo"`
	MissingTeethID             interface{} `json:"MissingTeethId"`
	IsMissingTeeth             interface{} `json:"IsMissingTeeth"`
	UL1                        interface{} `json:"UL1"`
	UR1                        interface{} `json:"UR1"`
	LR1                        interface{} `json:"LR1"`
	LL1                        interface{} `json:"LL1"`
	UL2                        interface{} `json:"UL2"`
	UR2                        interface{} `json:"UR2"`
	LR2                        interface{} `json:"LR2"`
	LL2                        interface{} `json:"LL2"`
	UL3                        interface{} `json:"UL3"`
	UR3                        interface{} `json:"UR3"`
	LR3                        interface{} `json:"LR3"`
	LL3                        interface{} `json:"LL3"`
	UL4                        interface{} `json:"UL4"`
	UR4                        interface{} `json:"UR4"`
	LR4                        interface{} `json:"LR4"`
	LL4                        interface{} `json:"LL4"`
	UL5                        interface{} `json:"UL5"`
	UR5                        interface{} `json:"UR5"`
	LR5                        interface{} `json:"LR5"`
	LL5                        interface{} `json:"LL5"`
	UL6                        interface{} `json:"UL6"`
	UR6                        interface{} `json:"UR6"`
	LR6                        interface{} `json:"LR6"`
	LL6                        interface{} `json:"LL6"`
	UL7                        interface{} `json:"UL7"`
	UR7                        interface{} `json:"UR7"`
	LR7                        interface{} `json:"LR7"`
	LL7                        interface{} `json:"LL7"`
	UL8                        interface{} `json:"UL8"`
	UR8                        interface{} `json:"UR8"`
	LR8                        interface{} `json:"LR8"`
	LL8                        interface{} `json:"LL8"`
	DUMMY                      interface{} `json:"DUMMY"`
}
